"use client";

import Link from "next/link";
import FadeIn from "@/components/fade-in";

interface HeroSectionProps {
  onCtaClick: () => void;
}

const GRADIENT = "linear-gradient(135deg, #FF3CAC 0%, #FF6B35 100%)";
const GRAD_TEXT: React.CSSProperties = {
  background: GRADIENT,
  WebkitBackgroundClip: "text",
  backgroundClip: "text",
  WebkitTextFillColor: "transparent",
};
const MONO = "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace";

export default function HeroSection({ onCtaClick }: HeroSectionProps) {
  return (
    <section style={{ background: "transparent", position: "relative" }}>

      {/* ── Subtle grid overlay ── */}
      <div style={{
        position: "absolute", inset: 0, pointerEvents: "none", zIndex: 0, opacity: 0.4,
        backgroundImage: [
          "linear-gradient(rgba(13,13,18,0.025) 1px, transparent 1px)",
          "linear-gradient(90deg, rgba(13,13,18,0.025) 1px, transparent 1px)",
        ].join(", "),
        backgroundSize: "64px 64px",
        WebkitMaskImage: "radial-gradient(ellipse 80% 60% at 50% 20%, black 0%, transparent 75%)",
        maskImage:       "radial-gradient(ellipse 80% 60% at 50% 20%, black 0%, transparent 75%)",
      }} />

      {/* ════════════ Centered hero copy ════════════ */}
      <div
        className="relative flex flex-col items-center text-center px-6 sm:px-8 pt-14 sm:pt-20"
        style={{ maxWidth: 1100, margin: "0 auto", zIndex: 1 }}
      >
        {/* Eyebrow */}
        <FadeIn delay={0.04}>
          <div style={{
            display: "inline-flex", alignItems: "center", gap: 8,
            background: "rgba(255,60,172,0.08)", border: "1px solid rgba(255,60,172,0.22)",
            color: "#FF3CAC", fontSize: 12, fontWeight: 700,
            letterSpacing: "0.1em", textTransform: "uppercase",
            padding: "7px 14px", borderRadius: 999, fontFamily: "var(--font-inter)",
          }}>
            <span style={{
              width: 7, height: 7, borderRadius: 999, background: "#FF3CAC",
              boxShadow: "0 0 8px #FF3CAC", animation: "adurPulse 2s ease-in-out infinite", flexShrink: 0,
            }} />
            <span>AI Creative Studio for E-commerce Brands</span>
          </div>
        </FadeIn>

        {/* Headline */}
        <FadeIn delay={0.1}>
          <h1
            className="font-heading"
            style={{
              fontSize: "clamp(40px, 5.6vw, 80px)",
              fontWeight: 900,
              lineHeight: 0.98,
              letterSpacing: "-0.045em",
              color: "#0D0D12",
              marginTop: 28,
            }}
          >
            Generate winning<br />
            <span style={GRAD_TEXT}>ad creatives in 30 seconds.</span>
          </h1>
        </FadeIn>

        {/* Subhead */}
        <FadeIn delay={0.16}>
          <p style={{
            marginTop: 24, fontSize: 19, lineHeight: 1.55, color: "#6B6B72",
            maxWidth: 560, fontFamily: "var(--font-inter)",
          }}>
            UGC videos. Static ads. Ad copy.{" "}
            <strong style={{ color: "#0D0D12", fontWeight: 600 }}>
              Everything your e-commerce store needs to scale on Meta
            </strong>{" "}
            — generated by AI in seconds. Free to try.
          </p>
        </FadeIn>

        {/* CTAs */}
        <FadeIn delay={0.22} className="w-full sm:w-auto">
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-center" style={{ marginTop: 36, gap: 12 }}>
            <button
              onClick={onCtaClick}
              className="inline-flex items-center justify-center gap-2 text-white cursor-pointer"
              style={{
                fontSize: 16, fontWeight: 700, fontFamily: "var(--font-inter)",
                background: GRADIENT, border: "none", borderRadius: 12,
                padding: "16px 28px", letterSpacing: "-0.01em",
                boxShadow: "0 4px 24px rgba(255,60,172,0.28)",
                transition: "box-shadow 0.2s, transform 0.15s",
              }}
              onMouseEnter={(e) => { const b = e.currentTarget; b.style.transform = "translateY(-1px)"; b.style.boxShadow = "0 8px 32px rgba(255,60,172,0.4)"; }}
              onMouseLeave={(e) => { const b = e.currentTarget; b.style.transform = "translateY(0)"; b.style.boxShadow = "0 4px 24px rgba(255,60,172,0.28)"; }}
            >
              ✦ Generate free creative →
            </button>
            <Link
              href="/analyze"
              className="inline-flex items-center justify-center gap-2"
              style={{
                fontSize: 16, fontWeight: 500, color: "#0D0D12", fontFamily: "var(--font-inter)",
                background: "#FFFFFF", border: "1.5px solid #E8E5E0", borderRadius: 12,
                padding: "14.5px 24px", textDecoration: "none",
                transition: "border-color 0.15s, box-shadow 0.15s",
              }}
              onMouseEnter={(e) => { const a = e.currentTarget; a.style.borderColor = "#D4D0CA"; a.style.boxShadow = "0 1px 3px rgba(0,0,0,0.06)"; }}
              onMouseLeave={(e) => { const a = e.currentTarget; a.style.borderColor = "#E8E5E0"; a.style.boxShadow = "none"; }}
            >
              Analyze my Meta ads
            </Link>
          </div>
        </FadeIn>

        {/* Trust row */}
        <FadeIn delay={0.28}>
          <div className="flex items-center justify-center flex-wrap" style={{
            marginTop: 24, gap: 12, fontSize: 13, color: "#A8A5A0",
            fontWeight: 500, fontFamily: "var(--font-inter)",
          }}>
            {["UGC videos", "Static ad images", "Ad copy"].map((label, i) => (
              <span key={label} style={{ display: "inline-flex", alignItems: "center", gap: 12 }}>
                {i > 0 && <span style={{ color: "#D4D0CA" }}>·</span>}
                <span style={{ display: "inline-flex", alignItems: "center", gap: 7 }}>
                  <span style={{ ...GRAD_TEXT, fontWeight: 700 }}>✦</span> {label}
                </span>
              </span>
            ))}
          </div>
        </FadeIn>

        {/* Proof pill */}
        <FadeIn delay={0.34}>
          <div style={{
            marginTop: 30, display: "inline-flex", alignItems: "center", gap: 10,
            background: "#0D0D12", color: "#fff",
            fontSize: 13.5, fontWeight: 600, fontFamily: "var(--font-inter)",
            padding: "10px 22px", borderRadius: 999,
            boxShadow: "0 8px 24px rgba(13,13,18,0.22)",
          }}>
            <span style={{ ...GRAD_TEXT, fontWeight: 800, flexShrink: 0 }}>✦</span>
            <span>Built by media buyers who&apos;ve managed $70M+ in ad spend</span>
          </div>
        </FadeIn>
      </div>

      {/* ════════════ Product preview ════════════ */}
      <div className="relative px-4 sm:px-8" style={{ maxWidth: 1100, margin: "52px auto 0", paddingBottom: 96, zIndex: 1 }}>
        <FadeIn delay={0.2}>
          <div style={{ position: "relative", maxWidth: 880, margin: "0 auto" }}>

            {/* Floating chips — desktop only */}
            {[
              { cls: "lg:flex", pos: { top: -22, left: -56,  transform: "rotate(-3deg)" },  glyph: "✓", glyphColor: "#16A34A", label: "Generated in 12s" },
              { cls: "lg:flex", pos: { top: -22, right: -56, transform: "rotate(2.5deg)" }, glyph: "⤓", glyphColor: null,      label: "Ready to download" },
              { cls: "lg:flex", pos: { bottom: 64, left: -72,  transform: "rotate(2deg)" },   glyph: "▶", glyphColor: null,    label: "UGC video ready" },
              { cls: "lg:flex", pos: { bottom: 64, right: -72, transform: "rotate(-2.5deg)" },glyph: "✦", glyphColor: null,    label: "5 ad copies generated" },
            ].map((c) => (
              <div
                key={c.label}
                className={`hidden ${c.cls} items-center`}
                style={{
                  position: "absolute", zIndex: 3, ...c.pos,
                  background: "#FFFFFF", border: "1px solid #E8E5E0", borderRadius: 12,
                  padding: "10px 16px", gap: 8, whiteSpace: "nowrap",
                  fontSize: 13, fontWeight: 600, color: "#0D0D12", fontFamily: "var(--font-inter)",
                  boxShadow: "0 16px 36px rgba(13,13,18,0.1), 0 4px 12px rgba(13,13,18,0.05)",
                }}
              >
                <span style={c.glyphColor ? { color: c.glyphColor, fontWeight: 800 } : { ...GRAD_TEXT, fontWeight: 800 }}>
                  {c.glyph}
                </span>
                <span>{c.label}</span>
              </div>
            ))}

            {/* Browser frame */}
            <div style={{
              background: "#FFFFFF", borderRadius: 16, border: "1px solid #E8E5E0", overflow: "hidden",
              boxShadow: "0 50px 100px -24px rgba(13,13,18,0.16), 0 24px 48px -16px rgba(255,60,172,0.08), 0 0 0 1px rgba(13,13,18,0.03)",
            }}>
              {/* Chrome */}
              <div style={{
                background: "#F7F5F2", height: 40, display: "flex", alignItems: "center",
                padding: "0 16px", gap: 14, borderBottom: "1px solid #E8E5E0",
              }}>
                <div style={{ display: "flex", gap: 6, flexShrink: 0 }}>
                  <span style={{ width: 11, height: 11, borderRadius: 999, background: "#FF5F57", display: "block" }} />
                  <span style={{ width: 11, height: 11, borderRadius: 999, background: "#FFBD2E", display: "block" }} />
                  <span style={{ width: 11, height: 11, borderRadius: 999, background: "#28C940", display: "block" }} />
                </div>
                <div style={{
                  background: "#FFFFFF", border: "1px solid #E8E5E0", borderRadius: 7,
                  padding: "4px 12px", fontFamily: MONO, fontSize: 11, color: "#A8A5A0",
                  flex: 1, maxWidth: 300, display: "flex", alignItems: "center", gap: 7, minWidth: 0,
                }}>
                  <span style={{ width: 8, height: 8, borderRadius: 999, background: "#16A34A", flexShrink: 0 }} />
                  <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>app.adur.ai/creative-studio</span>
                </div>
              </div>

              {/* Body */}
              <div className="p-4 sm:p-7" style={{ background: "#FAF8F5" }}>

                {/* Generated creatives grid — 2-up on mobile, 3-up from md */}
                <div className="grid grid-cols-2 md:grid-cols-[1fr_1.12fr_1fr] items-center gap-3 sm:gap-[18px]">

                  {/* Card 1 — dark bold type */}
                  <div className="flex flex-col justify-between" style={{
                    aspectRatio: "1 / 1", borderRadius: 12, overflow: "hidden", position: "relative",
                    background: "radial-gradient(ellipse 120% 90% at 30% 0%, #26262F 0%, #0D0D12 70%)",
                    padding: 18,
                    boxShadow: "0 4px 16px rgba(13,13,18,0.07), 0 1px 3px rgba(13,13,18,0.04)",
                  }}>
                    <div style={{ fontFamily: MONO, fontSize: 8.5, letterSpacing: "0.2em", textTransform: "uppercase", color: "rgba(255,255,255,0.45)" }}>
                      Adur · Static 01
                    </div>
                    <div className="font-heading" style={{ fontWeight: 900, color: "#fff", fontSize: "clamp(20px, 2.6vw, 30px)", lineHeight: 1.0, letterSpacing: "-0.03em" }}>
                      GLOW<br /><span style={GRAD_TEXT}>DIFFERENT</span>
                    </div>
                    <div style={{
                      alignSelf: "flex-start", fontSize: 9.5, fontWeight: 700, color: "#0D0D12",
                      background: "#fff", borderRadius: 999, padding: "5px 12px", fontFamily: "var(--font-inter)",
                    }}>
                      Shop now
                    </div>
                  </div>

                  {/* Card 2 — skincare product hero (center, elevated on desktop) */}
                  <div className="flex flex-col items-center justify-center md:-translate-y-3" style={{
                    aspectRatio: "1 / 1", borderRadius: 12, overflow: "hidden", position: "relative",
                    background: "linear-gradient(180deg, #FFFFFF 0%, #F0EDE8 100%)",
                    padding: 16, zIndex: 2,
                    boxShadow: "0 24px 48px -12px rgba(255,60,172,0.22), 0 8px 20px rgba(13,13,18,0.08)",
                  }}>
                    {/* bottle */}
                    <div style={{
                      width: "34%", aspectRatio: "0.42", position: "relative",
                      background: "linear-gradient(105deg, #E8E2D8 0%, #FDFCF9 45%, #D4D0CA 100%)",
                      borderRadius: "8px 8px 10px 10px",
                      boxShadow: "0 16px 28px rgba(120,105,80,0.28)",
                    }}>
                      {/* cap */}
                      <div style={{
                        position: "absolute", top: "-14%", left: "30%", right: "30%", height: "14%",
                        background: "linear-gradient(105deg, #B8AD99, #8F8470)", borderRadius: "4px 4px 0 0",
                      }} />
                      {/* label */}
                      <div style={{
                        position: "absolute", left: "10%", right: "10%", top: "38%",
                        background: "#fff", borderRadius: 3, padding: "14% 0",
                        fontFamily: MONO, fontSize: 7, letterSpacing: "0.16em",
                        color: "#6B6357", textAlign: "center",
                        boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
                      }}>
                        SERUM Nº4
                      </div>
                    </div>
                    <div style={{ marginTop: 14, fontSize: 12, fontWeight: 800, letterSpacing: "0.18em", textTransform: "uppercase", color: "#5B5346", fontFamily: "var(--font-inter)" }}>
                      The Ritual
                    </div>
                    {/* micro-line clips inside the square card below ~400px — desktop only */}
                    <div className="hidden sm:block" style={{ marginTop: 4, fontFamily: MONO, fontSize: 8, color: "#A8A5A0", letterSpacing: "0.1em", whiteSpace: "nowrap" }}>
                      CLINICALLY PROVEN · 28 DAYS
                    </div>
                  </div>

                  {/* Card 3 — warm lifestyle (hidden on mobile, like the mockup) */}
                  <div className="hidden md:flex flex-col justify-end" style={{
                    aspectRatio: "1 / 1", borderRadius: 12, overflow: "hidden", position: "relative",
                    background: [
                      "radial-gradient(ellipse 90% 60% at 70% 20%, rgba(255,255,255,0.3) 0%, transparent 60%)",
                      "linear-gradient(160deg, #FF6B35 0%, #E8506B 55%, #FF3CAC 130%)",
                    ].join(", "),
                    padding: 18,
                    boxShadow: "0 4px 16px rgba(13,13,18,0.07), 0 1px 3px rgba(13,13,18,0.04)",
                  }}>
                    <div style={{
                      position: "absolute", top: "16%", right: "18%", width: "26%", aspectRatio: "1",
                      borderRadius: 999,
                      background: "radial-gradient(circle at 35% 35%, #FFF3DA, #FFD9A0 70%)",
                      boxShadow: "0 0 36px rgba(255,235,190,0.7)",
                    }} />
                    <div className="font-heading" style={{
                      fontWeight: 800, color: "#fff", fontSize: "clamp(13px, 1.7vw, 19px)",
                      lineHeight: 1.1, letterSpacing: "-0.01em", position: "relative",
                      textShadow: "0 2px 10px rgba(160,40,90,0.3)",
                    }}>
                      Made for<br />golden hour.
                    </div>
                    <div style={{
                      marginTop: 6, fontFamily: MONO, fontSize: 8, fontWeight: 600,
                      color: "rgba(255,255,255,0.85)", letterSpacing: "0.14em", textTransform: "uppercase", position: "relative",
                    }}>
                      Summer drop · 24h only
                    </div>
                  </div>
                </div>

                {/* Prompt bar */}
                <div className="flex items-center" style={{
                  marginTop: 22, gap: 10,
                  background: "#FFFFFF", border: "1px solid #E8E5E0", borderRadius: 12,
                  padding: "8px 8px 8px 20px",
                  boxShadow: "inset 0 1px 2px rgba(13,13,18,0.03)",
                }}>
                  <span style={{
                    display: "inline-block", width: 1.5, height: 16,
                    background: "#FF3CAC", marginRight: 2, flexShrink: 0,
                    animation: "adurBlink 1.1s steps(1) infinite",
                  }} />
                  <span style={{
                    flex: 1, fontSize: 14, color: "#A8A5A0", fontFamily: "var(--font-inter)",
                    whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", textAlign: "left", minWidth: 0,
                  }}>
                    Premium skincare serum, luxury feel, white background...
                  </span>
                  <button
                    onClick={onCtaClick}
                    className="inline-flex items-center cursor-pointer"
                    style={{
                      flexShrink: 0, gap: 7, fontSize: 14, fontWeight: 700, color: "#fff",
                      fontFamily: "var(--font-inter)", background: GRADIENT,
                      border: "none", borderRadius: 9, padding: "11px 22px",
                      boxShadow: "0 4px 24px rgba(255,60,172,0.28)",
                      transition: "box-shadow 0.2s",
                    }}
                    onMouseEnter={(e) => { e.currentTarget.style.boxShadow = "0 8px 32px rgba(255,60,172,0.4)"; }}
                    onMouseLeave={(e) => { e.currentTarget.style.boxShadow = "0 4px 24px rgba(255,60,172,0.28)"; }}
                  >
                    ✦ Generate
                  </button>
                </div>
              </div>
            </div>
          </div>
        </FadeIn>
      </div>

      {/* keyframes */}
      <style>{`
        @keyframes adurPulse { 0%,100% { opacity: 1; transform: scale(1); } 50% { opacity: 0.5; transform: scale(0.85); } }
        @keyframes adurBlink { 50% { opacity: 0; } }
      `}</style>

    </section>
  );
}
